### ISSUE TITLE
[生成] -> [构建]

### ISSUE THREAD

**Issue by KHwang9883** [defisym/ClickteamFusion_ZH_CN#3]
**翻译建议**
`Build` 应翻译为 `构建`

**Comment by defisym** [comment]
`Build`翻译为`生成`参考了Visual Studio的本地化
[](url)
![79L$I}76DW3E 5LG1D@O}DL](https://user-images.githubusercontent.com/55148235/89102295-5657ae80-d43a-11ea-865f-3d842f34d52f.png)
![XR_@)EH{_ZC GVN8NF}TQ)6](https://user-images.githubusercontent.com/55148235/89102297-5ce62600-d43a-11ea-8957-6da9cdbaa9b2.png)
