### ISSUE TITLE
Edrt 和 mmf2u 的两个文件中缺少符号导致Clickteam Fusion无法使用汉化文件

### ISSUE THREAD

**Issue by 2659170494** [defisym/ClickteamFusion_ZH_CN#4]
因为我没有上传文件的权限，还求作者将这两个文件覆盖一下
原先的edrt和mmf2u会报232:2: Expected, before "和1963:41: Unexpected 'L' in object
[edrt.txt](https://github.com/defisym/ClickteamFusion_ZH_CN/files/8059763/edrt.txt)
[mmf2u.txt](https://github.com/defisym/ClickteamFusion_ZH_CN/files/8059765/mmf2u.txt)

**Comment by defisym** [comment]
应该是修改的时候出了语法错误，近期内会修复
另外，没有提交权限是因为你误解了GitHub的使用方式，如果不是协作者你是肯定没有权限提交到原始仓库的，你需要先fork一份到自己的仓库里，然后提交到自己的仓库，系统监测到你的仓库和原始仓库之间有版本差异，就会允许你给原始仓库发送pull request，这样原始仓库所有者就能看见你的修改，就可以选择合并或者拒绝你的提交，而不是在issue里附带修改后的文件

**Comment by defisym** [comment]
最新的commit修正了相关的语法错误，你可以Pull一下来查看是否修复了你的问题
